package itp.storage;
//parts of this code is generated by claude.ai
import java.io.File;
import java.io.IOException;

import com.fasterxml.jackson.databind.ObjectMapper;
import app.User;
import app.UserData;
import app.UserPersistence;
import app.FlashcardDeckManager;
import app.PasswordEncoder;

/**
 * Handles saving and loading user data (credentials + flashcards) to/from JSON files.
 * Fixed to prevent user credentials from being overwritten by flashcard data.
 */
public class FlashcardPersistent implements UserPersistence {

    private final ObjectMapper objectMapper;

    public FlashcardPersistent() {
        this.objectMapper = new ObjectMapper();
    }

    /**
     * Saves flashcard deck manager for a user while preserving credentials.
     */
    public void writeDeck(String username, FlashcardDeckManager deckManager) throws IOException {
        System.out.println("DEBUG: writeDeck called for user: " + username);
        
        // Read existing user data first
        UserData userData = readUserDataInternal(username);
        
        if (userData == null) {
            System.out.println("DEBUG: No user data found, creating new UserData for: " + username);
            
            userData = new UserData();
            userData.setUsername(username);
            
        }
        
        System.out.println("DEBUG: Updating deck for user: " + username);
        // Update only the deck manager, keep credentials
        userData.setDeckManager(deckManager);
        
        // Write back the complete user data
        writeUserDataInternal(userData);
        System.out.println("DEBUG: Successfully wrote deck for user: " + username);
    }

    /**
     * Loads flashcard deck manager for a user.
     */
    public FlashcardDeckManager readDeck(String username) throws IOException {
        System.out.println("DEBUG: readDeck called for user: " + username);
        
        UserData userData = readUserDataInternal(username);
        
        if (userData != null) {
            System.out.println("DEBUG: Found user data, returning deck manager for: " + username);
            return userData.getDeckManager();
        } else {
            System.out.println("DEBUG: No user data found, returning empty deck manager for: " + username);
            return new FlashcardDeckManager();
        }
    }

    /**
     * Checks if user data exists.
     */
    public boolean dataExists(String username) {
        File file = getUserFile(username);
        boolean exists = file.exists();
        System.out.println("DEBUG: dataExists for " + username + ": " + exists);
        return exists;
    }

    @Override
    public User readUserData(String username) {
        System.out.println("DEBUG: readUserData called for: " + username);
        
        UserData userData = readUserDataInternal(username);
        User result = userData != null ? userData.toUser() : null;
        
        System.out.println("DEBUG: readUserData result for " + username + ": " + (result != null ? "found" : "null"));
        return result;
    }

    @Override
    public void writeUserData(User user) throws IOException {
        System.out.println("DEBUG: writeUserData called for: " + user.getUsername());
        
        UserData existingData = readUserDataInternal(user.getUsername());

        if (existingData != null) {
            System.out.println("DEBUG: User exists, updating credentials for: " + user.getUsername());
            // User exists, update credentials but keep deck data
            existingData.setUsername(user.getUsername());
            existingData.setPassword(PasswordEncoder.encode(user.getPassword()));
            writeUserDataInternal(existingData);
        } else {
            System.out.println("DEBUG: New user, creating fresh user data for: " + user.getUsername());
            // New user, create fresh user data
            UserData userData = new UserData(user.getUsername(), PasswordEncoder.encode(user.getPassword()));
            writeUserDataInternal(userData);
        }
        
        System.out.println("DEBUG: Successfully wrote user data for: " + user.getUsername());
    }

    @Override
    public boolean userExists(String username) {
        System.out.println("DEBUG: userExists called for: " + username);
        
        UserData userData = readUserDataInternal(username);
        boolean exists = userData != null && userData.getUsername() != null && userData.getPassword() != null;
        
        System.out.println("DEBUG: userExists result for " + username + ": " + exists);
        return exists;
    }

    /**
     * Internal method to read complete user data from file.
     */
    private UserData readUserDataInternal(String username) {
        System.out.println("DEBUG: readUserDataInternal called for: " + username);
        
        File file = getUserFile(username);

        if (file.exists()) {
            System.out.println("DEBUG: File exists for: " + username);
            
            try {
                // Try to read as new format (UserData)
                UserData userData = objectMapper.readValue(file, UserData.class);
                System.out.println("DEBUG: Successfully read as UserData for: " + username);
                return userData;
            } catch (Exception e) {
                System.out.println("DEBUG: Failed to read as UserData, trying User format for: " + username);
                
                try {
                    // Try to read as old format (just User)
                    User user = objectMapper.readValue(file, User.class);
                    System.out.println("DEBUG: Successfully read as User, converting to UserData for: " + username);
                    return new UserData(user.getUsername(), user.getPassword());
                } catch (Exception e2) {
                    System.out.println("DEBUG: Failed to read as User, trying FlashcardDeckManager for: " + username);
                    
                    try {
                        // Try to read as very old format (just FlashcardDeckManager)
                        FlashcardDeckManager deckManager = objectMapper.readValue(file, FlashcardDeckManager.class);
                        System.out.println("File exists but doesn't contain user credentials: " + username);
                        return null;
                    } catch (Exception e3) {
                        System.err.println("Failed to read user data for: " + username + " - " + e3.getMessage());
                        return null;
                    }
                }
            }
        } else {
            System.out.println("DEBUG: No file exists for: " + username);
        }
        
        return null;
    }

    /**
     * Internal method to write complete user data to file.
     */
    private void writeUserDataInternal(UserData userData) throws IOException {
        System.out.println("DEBUG: writeUserDataInternal called for: " + userData.getUsername());
        
        File dataDir = new File(System.getProperty("user.dir") + "/../storage/data/users");
        if (!dataDir.exists()) {
            boolean created = dataDir.mkdirs();
            if (!created) {
                throw new IOException("Failed to create data directory: " + dataDir.getAbsolutePath());
            }
        }
        
        File file = getUserFile(userData.getUsername());
        objectMapper.writerWithDefaultPrettyPrinter().writeValue(file, userData);
        
        System.out.println("DEBUG: Successfully wrote UserData to file: " + file.getAbsolutePath());
    }

    /**
     * Gets the file for a specific username.
     */
    private File getUserFile(String username) {
        String path = System.getProperty("user.dir") + "/../storage/data/users/" + username + ".json";
        System.out.println("DEBUG: getUserFile for " + username + ": " + path);
        return new File(path);
    }
}